[package]
name = "cornulike"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gen_math_lib = {git = "https://github.com/Dzuchun/Rust-Math-Lib"}